### PR TITLE
create body of email using last change log entry

### PR DESCRIPTION
**Pull request by dod38fr**
Hello

I've improved your EmailNotify plugin to send mail with more interesting content for the users: the email will contain the change log of the release. 

See this example of a mail generated with this version of EmailNotify: 
http://sourceforge.net/mailarchive/message.php?msg_id=31407841

I'll package this plugin for Debian once the new version hits CPAN.

All the best

### CODE REVIEW

**Comment by dod38fr** [comment]
Email::Stuff is now deprecated. This PR replaces it with Email::Stuffer

**Comment by xsawyerx** [comment]
Ooo! Fancy! How did I miss this?

**Comment by dod38fr** [comment]
heh, like me, you probably juggle with too many balls. Some of them fall down... Don't worry about it.

All the best

**Comment by xsawyerx** [comment]
Gonna release now!

**Comment by xsawyerx** [comment]
This one is all you. :+1:

**Comment by dod38fr** [comment]
Thanks. This package will soon be available on Debian: 
https://ftp-master.debian.org/new/libdist-zilla-plugin-emailnotify-perl_0.003-1.html

All the best

**Pull request merged**
